import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API='http://localhost:8330/api';
type Result={job_id:string,claim_mapping:any[],claims:any[],preamble:string,summary:string,summary_similarity:string,summary_difference:string,validation:string[]};
function App(){
 const [tab,setTab]=useState('analysis'),[claims,setClaims]=useState(''),[files,setFiles]=useState<File[]>([]),[effort,setEffort]=useState('medium'),[result,setResult]=useState<Result|null>(null),[history,setHistory]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[settings,setSettings]=useState({provider:'agy',command:'agy',model:'gemini-3.6-flash-medium',prompt:''}),[models,setModels]=useState<string[]>([]);
 useEffect(()=>{fetch(API+'/history').then(r=>r.json()).then(setHistory).catch(()=>{});fetch(API+'/settings').then(r=>r.json()).then(s=>{setSettings(s);loadModels(s)}).catch(()=>{})},[]);
 async function loadModels(next:any,refresh=false){try{const q=new URLSearchParams({provider:next.provider,command:next.command,...(refresh?{refresh:'true'}:{})});const r=await fetch(API+'/settings/models?'+q);const data=await r.json();setModels(r.ok&&Array.isArray(data.models)?data.models:[]);if(refresh)setMessage(data.models?.length?`모델 ${data.models.length}개를 불러왔습니다.`:'모델 목록을 불러오지 못했습니다. 모델명을 직접 입력하세요.')}catch{setModels([])}}
 function changeProvider(provider:string){const next={...settings,provider,command:provider};setSettings(next);loadModels(next)}
 async function saveSettings(next=settings){const r=await fetch(API+'/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const data=await r.json();if(r.ok)setSettings(data);setMessage(r.ok?'설정을 저장했습니다.':'저장 실패: '+(data.detail||''))}
 async function resetPrompt(){await saveSettings({...settings,prompt:''});setMessage('분석 지시 프롬프트를 기본값으로 되돌렸습니다.')}
 async function testSettings(){const r=await fetch(API+'/settings/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});const data=await r.json();setMessage(data.message)}
 async function run(){if(!claims.trim()||!files.length){setMessage('청구항과 PDF를 모두 입력해 주세요.');return} setBusy(true);setMessage('문서 추출과 비교 분석을 진행 중입니다…');const form=new FormData();form.append('claims',claims);form.append('agy_reasoning_effort',effort);form.append('analysis_prompt',settings.prompt||'');files.forEach(f=>form.append('pdf_files',f));try{const r=await fetch(API+'/jobs',{method:'POST',body:form});const job=await r.json();if(!r.ok)throw new Error(job.detail);setResult(await (await fetch(API+'/jobs/'+job.job_id+'/result')).json());setTab('result');setMessage('분석이 완료되었습니다.')}catch(e:any){setMessage(e.message||'분석에 실패했습니다.')}finally{setBusy(false)}}
 async function removeHistory(id:string){if(!confirm('이 분석 기록과 작업 로그를 삭제합니다. 되돌릴 수 없습니다. 계속할까요?'))return;const r=await fetch(API+'/history/'+id,{method:'DELETE'});if(!r.ok){setMessage('삭제에 실패했습니다.');return}setHistory(history.filter(h=>h.job_id!==id));setMessage('분석 기록을 삭제했습니다.')}
 async function clearHistory(){if(!history.length)return;if(!confirm(`저장된 분석 기록 ${history.length}건과 모든 작업 로그를 삭제합니다. 되돌릴 수 없습니다. 계속할까요?`))return;const r=await fetch(API+'/history',{method:'DELETE'});const data=await r.json();if(!r.ok){setMessage('삭제에 실패했습니다.');return}setHistory([]);setMessage(`분석 기록 ${data.removed}건과 작업 로그를 모두 삭제했습니다.`)}
 async function load(id:string){const r=await fetch(API+'/history/'+id);const data=await r.json();if(!r.ok||!data.result){setMessage('이 분석의 상세 결과가 저장되어 있지 않습니다. 리포트 다운로드만 가능합니다.');return}setResult(data.result);setMessage('');setTab('result')}
 const source=(e:any)=>[e.reference_number?`인용발명 ${e.reference_number}`:e.filename,e.document_number&&`(${e.document_number})`,e.paragraph?`단락 [${e.paragraph}]`:e.page&&`p.${e.page}`].filter(Boolean).join(' ');
 return <div className="app"><header><div className="brand"><span className="mark" aria-hidden="true"><i/><b>F</b></span><div><b>Evidence Forge</b><small>특허 · 기술 문헌 분석</small></div></div><nav aria-label="주요 메뉴">{[['analysis','분석'],['history','히스토리'],['logs','로그'],['settings','설정']].map(([id,label],index)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>0{index+1}</span>{label}</button>)}</nav><span className="status"><i/> SYSTEM READY</span></header>
 {tab==='analysis'&&<main><section className="hero"><div className="hero-copy"><p className="eyebrow"><span>NEW</span> AI-POWERED PRIOR ART REVIEW</p><h1>복잡한 문헌 비교를<br/><em>명확한 근거</em>로 바꿉니다.</h1><p className="sub">청구항과 PDF를 업로드하면 문서 유형을 분류하고, 구성요소별 선행기술 근거를 찾아 비교 리포트를 생성합니다.</p></div><div className="hero-stamp" aria-hidden="true"><span>EVIDENCE</span><b>→</b><span>FORGED</span><small>EST. 2026 / SEOUL</small></div></section><section className="grid"><div className="card input-card"><span className="card-index">01 / CLAIM</span><label>분석할 청구항</label><textarea value={claims} onChange={e=>setClaims(e.target.value)} placeholder="예: (A) 메모리 컨트롤러가 쓰기 요청을 순차 처리하는 단계..."/><div className="row"><span className="hint">구성요소를 (A), (B), (C)로 구분하면 그 라벨 그대로 대비합니다.</span><span>{claims.length}자</span></div></div><div className="card upload-card"><span className="card-index">02 / SOURCE</span><label>참조 문헌 <span className="muted">PDF · 최대 7개</span></label><label className="drop"><input type="file" accept="application/pdf" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,7))}/><span className="drop-icon">↳</span><strong>파일을 여기에 놓거나 클릭하세요</strong><small>PDF만 지원 · 파일당 최대 25MB</small></label>{files.map((f,i)=><div key={f.name+f.size+f.lastModified} className="file"><span>PDF</span>{f.name}<button onClick={()=>setFiles(files.filter((_,x)=>x!==i))}>×</button></div>)}</div></section>
 <details className="card prompt-card"><summary>분석 지시 프롬프트 <span className="muted">이 지시문이 그대로 LLM에 전달됩니다</span></summary><textarea value={settings.prompt} onChange={e=>setSettings({...settings,prompt:e.target.value})}/><div className="row"><span className="hint">저장하지 않아도 이번 분석에는 위 내용이 사용됩니다.</span><span>{(settings.prompt||'').length}자</span></div><div className="prompt-actions"><button onClick={resetPrompt}>기본값 복원</button><button onClick={()=>saveSettings()}>프롬프트 저장</button></div></details>
 <div className="action"><div><b>분석 설정</b><select value={effort} onChange={e=>setEffort(e.target.value)}><option value="low">low · 빠른 분석</option><option value="medium">medium · 권장</option><option value="high">high · 정밀 분석</option></select></div><button className="primary" disabled={busy} onClick={run}>{busy?'분석 중…':'분석 시작  →'}</button></div>{message&&<div className="notice">{message}</div>}</main>}
 {tab==='result'&&<main><div className="topline"><div><p className="eyebrow">ANALYSIS RESULT</p><h2>구성대비 결과</h2></div>{result&&<div><a className="download" href={`${API}/jobs/${result.job_id}/download?format=md`}>Markdown 다운로드</a></div>}</div>{result&&<><div className="mapping card"><h3>문헌 매핑 테이블</h3>{result.claim_mapping.map(m=><div key={m.document_id} className="mapping-row"><b>인용발명 {m.reference_number}</b><span>{m.filename}</span><small>{[m.document_number,m.role||m.document_type].filter(Boolean).join(' · ')}</small></div>)}</div>{result.preamble&&<p className="sub">{result.preamble}</p>}<div className="results">{result.claims.map((c,i)=><article key={c.label||i} className="card claim"><div className="claim-head"><span className="badge">({c.label||String.fromCharCode(65+i)})</span><strong>{c.similarity==null?'—':c.similarity+'%'}</strong><span className="quality">{c.emoji} {c.grade||c.status}</span>{c.combination&&<span className="quality">결합</span>}</div><p>{c.claim}</p>{(c.narrative||c.note)&&<div className="narrative">{c.narrative||c.note}</div>}{c.difference&&<div className="diff">→ 차이점: {c.difference}</div>}{c.narrative&&c.note&&<small>{c.note}</small>}{c.evidence.map((e:any,j:number)=><blockquote key={j}><b>{e.quality} · {source(e)}</b><br/>{e.excerpt}{e.original_excerpt&&<><br/><i>{e.original_excerpt}</i></>}</blockquote>)}</article>)}</div><div className="summary"><h3>종합 분석 요약</h3>{result.summary_similarity&&<p>- 유사점: {result.summary_similarity}</p>}{result.summary_difference&&<p>- 차이점: {result.summary_difference}</p>}{result.summary&&<p>{result.summary}</p>}</div>{!!result.validation?.length&&<div className="card"><h3>검증 참고</h3>{result.validation.map((v,i)=><small key={i} style={{display:'block'}}>· {v}</small>)}</div>}</>}</main>}
 {tab==='history'&&<main><div className="topline"><div><p className="eyebrow">ARCHIVE</p><h2>분석 히스토리</h2></div><button className="danger" disabled={!history.length} onClick={clearHistory}>전체 삭제</button></div><div className="card list">{history.length?history.map(h=><div key={h.job_id} className="list-row"><button onClick={()=>load(h.job_id)}><b>{h.created_at.slice(0,16).replace('T',' ')}</b><span>{h.documents?.join(', ')}</span><small>결과 보기 →</small></button><button className="row-del" title="이 기록 삭제" onClick={()=>removeHistory(h.job_id)}>×</button></div>):<p className="empty">저장된 분석이 없습니다.</p>}</div><p className="sub">분석 결과·리포트는 <code>backend/data/history</code>, 작업 로그는 <code>backend/data/logs</code>에 저장됩니다. 삭제하면 두 곳에서 함께 지워집니다.</p>{message&&<div className="notice">{message}</div>}</main>}
 {tab==='settings'&&<main><p className="eyebrow">CONFIGURATION</p><h2>설정</h2><div className="card settings"><label>연동 CLI<select value={settings.provider} onChange={e=>changeProvider(e.target.value)}><option value="agy">agy</option><option value="claude">claude -p</option><option value="gpt">gpt -p</option></select></label><label>실행 명령어<input value={settings.command} onChange={e=>setSettings({...settings,command:e.target.value})} onBlur={()=>loadModels(settings)} placeholder="agy 또는 C:\\경로\\agy.cmd"/></label><label>모델<select value={models.includes(settings.model)?settings.model:'__custom__'} onChange={e=>setSettings({...settings,model:e.target.value==='__custom__'?'':e.target.value})}>{models.map(m=><option key={m} value={m}>{m}</option>)}<option value="__custom__">직접 입력…</option></select><button className="ghost" onClick={()=>loadModels(settings,true)}>모델 목록 새로고침</button></label>{!models.includes(settings.model)&&<label>모델명 직접 입력<input value={settings.model} onChange={e=>setSettings({...settings,model:e.target.value})} placeholder="예: gemini-3.6-flash-medium"/></label>}<p className="hint">agy 모델명은 <code>-low/-medium/-high</code> 접미사로 reasoning effort를 포함하므로, 아래 effort를 바꾸면 접미사를 자동으로 교체해 호출합니다.</p><label>reasoning effort<select value={effort} onChange={e=>setEffort(e.target.value)}><option value="low">low</option><option value="medium">medium</option><option value="high">high</option></select></label><label>분석 지시 프롬프트<textarea className="prompt-input" value={settings.prompt} onChange={e=>setSettings({...settings,prompt:e.target.value})}/></label><div className="action"><button onClick={testSettings}>연결 테스트</button><button onClick={resetPrompt}>프롬프트 기본값 복원</button><button className="primary" onClick={()=>saveSettings()}>설정 저장</button></div><p>백엔드가 실행되는 환경에서 CLI가 설치되어 있어야 합니다.</p>{message&&<div className="notice">{message}</div>}</div></main>}
 {tab==='logs'&&<main><p className="eyebrow">OBSERVABILITY</p><h2>작업 로그</h2><div className="card list"><p>로그는 작업별로 backend/data/logs에 저장되며 API에서 조회·수정할 수 있습니다.</p></div></main>}
 </div>}
createRoot(document.getElementById('root')!).render(<App/>);
